#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Wubipaws.Mobile.Droid.Resource", IsApplication=true)]

namespace Wubipaws.Mobile.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::Wubipaws.Mobile.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::Wubipaws.Mobile.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::Wubipaws.Mobile.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::Wubipaws.Mobile.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::Wubipaws.Mobile.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::Wubipaws.Mobile.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::Wubipaws.Mobile.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::Wubipaws.Mobile.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::Wubipaws.Mobile.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::Wubipaws.Mobile.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::Wubipaws.Mobile.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::Wubipaws.Mobile.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::Wubipaws.Mobile.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::Wubipaws.Mobile.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::Wubipaws.Mobile.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::Wubipaws.Mobile.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::Wubipaws.Mobile.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::Wubipaws.Mobile.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::Wubipaws.Mobile.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::Wubipaws.Mobile.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::Wubipaws.Mobile.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::Wubipaws.Mobile.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::Wubipaws.Mobile.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::Wubipaws.Mobile.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::Wubipaws.Mobile.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::Wubipaws.Mobile.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::Wubipaws.Mobile.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::Wubipaws.Mobile.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::Wubipaws.Mobile.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::Wubipaws.Mobile.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::Wubipaws.Mobile.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::Wubipaws.Mobile.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::Wubipaws.Mobile.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::Wubipaws.Mobile.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::Wubipaws.Mobile.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::Wubipaws.Mobile.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::Wubipaws.Mobile.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::ModernHttpClient.Resource.String.library_name = global::Wubipaws.Mobile.Droid.Resource.String.library_name;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Wubipaws.Mobile.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Wubipaws.Mobile.Droid.Resource.String.Hello;
			global::XLabs.Forms.Droid.Resource.Color.calendar_active_month_bg = global::Wubipaws.Mobile.Droid.Resource.Color.calendar_active_month_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_bg = global::Wubipaws.Mobile.Droid.Resource.Color.calendar_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_divider = global::Wubipaws.Mobile.Droid.Resource.Color.calendar_divider;
			global::XLabs.Forms.Droid.Resource.Color.calendar_highlighted_day_bg = global::Wubipaws.Mobile.Droid.Resource.Color.calendar_highlighted_day_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_inactive_month_bg = global::Wubipaws.Mobile.Droid.Resource.Color.calendar_inactive_month_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_selected_day_bg = global::Wubipaws.Mobile.Droid.Resource.Color.calendar_selected_day_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_selected_range_bg = global::Wubipaws.Mobile.Droid.Resource.Color.calendar_selected_range_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_active = global::Wubipaws.Mobile.Droid.Resource.Color.calendar_text_active;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_inactive = global::Wubipaws.Mobile.Droid.Resource.Color.calendar_text_inactive;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_selected = global::Wubipaws.Mobile.Droid.Resource.Color.calendar_text_selected;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_selector = global::Wubipaws.Mobile.Droid.Resource.Color.calendar_text_selector;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_unselectable = global::Wubipaws.Mobile.Droid.Resource.Color.calendar_text_unselectable;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_day_headers_paddingbottom = global::Wubipaws.Mobile.Droid.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_month_title_bottommargin = global::Wubipaws.Mobile.Droid.Resource.Dimension.calendar_month_title_bottommargin;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_month_topmargin = global::Wubipaws.Mobile.Droid.Resource.Dimension.calendar_month_topmargin;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_text_medium = global::Wubipaws.Mobile.Droid.Resource.Dimension.calendar_text_medium;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_text_small = global::Wubipaws.Mobile.Droid.Resource.Dimension.calendar_text_small;
			global::XLabs.Forms.Droid.Resource.Drawable.ad16 = global::Wubipaws.Mobile.Droid.Resource.Drawable.ad16;
			global::XLabs.Forms.Droid.Resource.Drawable.calendar_bg_selector = global::Wubipaws.Mobile.Droid.Resource.Drawable.calendar_bg_selector;
			global::XLabs.Forms.Droid.Resource.Id.calendar_grid = global::Wubipaws.Mobile.Droid.Resource.Id.calendar_grid;
			global::XLabs.Forms.Droid.Resource.Id.calendar_view = global::Wubipaws.Mobile.Droid.Resource.Id.calendar_view;
			global::XLabs.Forms.Droid.Resource.Id.calendarr_pager = global::Wubipaws.Mobile.Droid.Resource.Id.calendarr_pager;
			global::XLabs.Forms.Droid.Resource.Id.left_arrow = global::Wubipaws.Mobile.Droid.Resource.Id.left_arrow;
			global::XLabs.Forms.Droid.Resource.Id.right_arrow = global::Wubipaws.Mobile.Droid.Resource.Id.right_arrow;
			global::XLabs.Forms.Droid.Resource.Id.title = global::Wubipaws.Mobile.Droid.Resource.Id.title;
			global::XLabs.Forms.Droid.Resource.Layout.calendar_pager = global::Wubipaws.Mobile.Droid.Resource.Layout.calendar_pager;
			global::XLabs.Forms.Droid.Resource.Layout.calendar_pager_layout = global::Wubipaws.Mobile.Droid.Resource.Layout.calendar_pager_layout;
			global::XLabs.Forms.Droid.Resource.Layout.calendar_picker = global::Wubipaws.Mobile.Droid.Resource.Layout.calendar_picker;
			global::XLabs.Forms.Droid.Resource.Layout.dialog = global::Wubipaws.Mobile.Droid.Resource.Layout.dialog;
			global::XLabs.Forms.Droid.Resource.Layout.month = global::Wubipaws.Mobile.Droid.Resource.Layout.month;
			global::XLabs.Forms.Droid.Resource.Layout.week = global::Wubipaws.Mobile.Droid.Resource.Layout.week;
			global::XLabs.Forms.Droid.Resource.String.ApplicationName = global::Wubipaws.Mobile.Droid.Resource.String.ApplicationName;
			global::XLabs.Forms.Droid.Resource.String.Hello = global::Wubipaws.Mobile.Droid.Resource.String.Hello;
			global::XLabs.Forms.Droid.Resource.String.day_name_format = global::Wubipaws.Mobile.Droid.Resource.String.day_name_format;
			global::XLabs.Forms.Droid.Resource.String.full_date_format = global::Wubipaws.Mobile.Droid.Resource.String.full_date_format;
			global::XLabs.Forms.Droid.Resource.String.invalid_date = global::Wubipaws.Mobile.Droid.Resource.String.invalid_date;
			global::XLabs.Forms.Droid.Resource.String.library_name = global::Wubipaws.Mobile.Droid.Resource.String.library_name;
			global::XLabs.Forms.Droid.Resource.String.month_name_format = global::Wubipaws.Mobile.Droid.Resource.String.month_name_format;
			global::XLabs.Forms.Droid.Resource.Style.CalendarCell = global::Wubipaws.Mobile.Droid.Resource.Style.CalendarCell;
			global::XLabs.Forms.Droid.Resource.Style.CalendarCell_CalendarDate = global::Wubipaws.Mobile.Droid.Resource.Style.CalendarCell_CalendarDate;
			global::XLabs.Forms.Droid.Resource.Style.CalendarCell_DayHeader = global::Wubipaws.Mobile.Droid.Resource.Style.CalendarCell_DayHeader;
			global::XLabs.Forms.Droid.Resource.Style.CalendarTitle = global::Wubipaws.Mobile.Droid.Resource.Style.CalendarTitle;
			global::XLabs.Platform.Resource.String.ApplicationName = global::Wubipaws.Mobile.Droid.Resource.String.ApplicationName;
			global::XLabs.Platform.Resource.String.Hello = global::Wubipaws.Mobile.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int calendar_active_month_bg = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int calendar_bg = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int calendar_divider = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int calendar_highlighted_day_bg = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int calendar_inactive_month_bg = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int calendar_selected_day_bg = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int calendar_selected_range_bg = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int calendar_text_active = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int calendar_text_inactive = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int calendar_text_selected = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int calendar_text_selector = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int calendar_text_unselectable = 2131034122;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int calendar_day_headers_paddingbottom = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int calendar_month_title_bottommargin = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int calendar_month_topmargin = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int calendar_text_medium = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int calendar_text_small = 2131099652;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_bottom_solid_example = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_solid_example = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_stacked_solid_example = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_texture_tile_example = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_transparent_example = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int about = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int actionbar_tab_indicator = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ad16 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int boarding = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_default_example = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_cab_done_focused_example = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_cab_done_pressed_example = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int cab_background_bottom_example = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int cab_background_top_example = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int calendar_bg_selector = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int dog45 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_account_box_black_24dp = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_errorstatus = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_exit_to_app_black_24dp = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_exit_to_app_black_48dp = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_help_black_24dp = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_list_black_48dp = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_listitems_24dp = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_menu_black_24dp = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_person_outline_black_48dp = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_successstatus = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int icon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ios_arrow_right = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int list_focused_example = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int list_pressed_example = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int menu_dropdown_panel_example = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int pet_icon = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int progress_bg_example = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int progress_primary_example = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int progress_secondary_example = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int roundedbg = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int roundedbgdark = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int rubyfull = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int rubyfull320x311 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int scissors35 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int spinner_ab_default_example = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int spinner_ab_disabled_example = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int spinner_ab_focused_example = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int spinner_ab_pressed_example = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int tab_selected_example = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int tab_selected_focused_example = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int tab_selected_pressed_example = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int tab_unselected_example = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int tab_unselected_focused_example = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int tab_unselected_pressed_example = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int wubi_header_logo = 2130837554;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int calendar_grid = 2131230729;
			
			// aapt resource value: 0x7f080002
			public const int calendar_view = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int calendarr_pager = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int left_arrow = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int loadingImage = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int loadingProgressBar = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int loadingProgressWheel = 2131230728;
			
			// aapt resource value: 0x7f080003
			public const int right_arrow = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int textViewStatus = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int title = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_pager = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int calendar_pager_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int calendar_picker = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int loading = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int loadingimage = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int loadingprogress = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int month = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int week = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int day_name_format = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int full_date_format = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int invalid_date = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int month_name_format = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int CalendarCell = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int CalendarCell_CalendarDate = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int CalendarCell_DayHeader = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int CalendarTitle = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int MyActionBar = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int MyActionBarTabs = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int MyActionBarText = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int WubiPawsAppTheme = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int WubiPawsAppTheme_Base = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
